SiUbs/SiUbs.WebApp/Models/Cliente.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace SiUbs.WebApp.Models
{
    [Table("Clientes")]
    public class Cliente
    {
        public enum GeneroSexual
        {
            Masculino,
            Feminino
        }

        [Key]
        public int Id { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public string Nome { get; set; }
        [Display(Name = "Data de Nascimento")]
        [Required(ErrorMessage = "Campo Requerido")]
        [DataType(DataType.Date), DisplayFormat(DataFormatString = "{0:dd/MM/yyyy}", ApplyFormatInEditMode = true)]
        public DateTime DataDeNascimento { get; set; }
        [Required(ErrorMessage = "Campo Requerido")]
        public GeneroSexual Sexo { get; set; }

        virtual public ICollection<AfericaoGlicemia> AfericoesGlicemia { get; set; }
        virtual public ICollection<AfericaoPressaoArterial> AfericoesPressaoArterial { get; set; }
    }
}

SiUbs/SiUbs.WebApp/Controllers/AfericoesGlicemiaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiUbs.WebApp.Models;

namespace SiUbs.WebApp.Controllers
{
    [Authorize]
    public class AfericoesGlicemiaController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AfericoesGlicemia
        public ActionResult Index()
        {
            var afericoesGlicemia = db.AfericoesGlicemia.Include(a => a.Cliente);
            return View(afericoesGlicemia.ToList());
        }

        // GET: AfericoesGlicemia/ByCliente/5
        public ActionResult ByCliente(int id)
        {
            ViewBag.Cliente = id;
            var afericaoGlicemia = db.AfericoesGlicemia.Where(g => g.ClienteId == id);
            return View(afericaoGlicemia);
        }

        // GET: AfericoesGlicemia/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoGlicemia afericaoGlicemia = db.AfericoesGlicemia.Find(id);
            if (afericaoGlicemia == null)
            {
                return HttpNotFound();
            }
            return View(afericaoGlicemia);
        }

        // GET: AfericoesGlicemia/Create
        public ActionResult Create(int id)
        {
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome",id);
            return View();
        }

        // POST: AfericoesGlicemia/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DataHoraAfericao,Valor,Jejum,ClienteId")] AfericaoGlicemia afericaoGlicemia)
        {
            if (ModelState.IsValid)
            {
                db.AfericoesGlicemia.Add(afericaoGlicemia);
                db.SaveChanges();
                return RedirectToAction("ByCliente", new { id = afericaoGlicemia.ClienteId });
            }

            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoGlicemia.ClienteId);
            return View(afericaoGlicemia);
        }

        // GET: AfericoesGlicemia/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoGlicemia afericaoGlicemia = db.AfericoesGlicemia.Find(id);
            if (afericaoGlicemia == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoGlicemia.ClienteId);
            return View(afericaoGlicemia);
        }

        // POST: AfericoesGlicemia/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DataHoraAfericao,Valor,Jejum,ClienteId")] AfericaoGlicemia afericaoGlicemia)
        {
            if (ModelState.IsValid)
            {
                db.Entry(afericaoGlicemia).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ByCliente", new { id = afericaoGlicemia.ClienteId });
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoGlicemia.ClienteId);
            return View(afericaoGlicemia);
        }

        // GET: AfericoesGlicemia/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoGlicemia afericaoGlicemia = db.AfericoesGlicemia.Find(id);
            if (afericaoGlicemia == null)
            {
                return HttpNotFound();
            }
            return View(afericaoGlicemia);
        }

        // POST: AfericoesGlicemia/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AfericaoGlicemia afericaoGlicemia = db.AfericoesGlicemia.Find(id);
            db.AfericoesGlicemia.Remove(afericaoGlicemia);
            db.SaveChanges();
            return RedirectToAction("ByCliente", new { id = afericaoGlicemia.ClienteId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiUbs/SiUbs.WebApp/Controllers/AfericoesPressaoArterialController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SiUbs.WebApp.Models;

namespace SiUbs.WebApp.Controllers
{
    [Authorize]
    public class AfericoesPressaoArterialController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: AfericoesPressaoArterial
        public ActionResult Index()
        {
            var afericoesPressaoArterial = db.AfericoesPressaoArterial.Include(a => a.Cliente);
            return View(afericoesPressaoArterial.ToList());
        }

        // GET: AfericoesPressaoArterial/ByCliente/5
        public ActionResult ByCliente(int id)
        {
            ViewBag.Cliente = id;
            var afericaoPressaoArterial = db.AfericoesPressaoArterial.Where(p => p.ClienteId == id);
            return View(afericaoPressaoArterial);
        }

        // GET: AfericoesPressaoArterial/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoPressaoArterial afericaoPressaoArterial = db.AfericoesPressaoArterial.Find(id);
            if (afericaoPressaoArterial == null)
            {
                return HttpNotFound();
            }
            return View(afericaoPressaoArterial);
        }

        // GET: AfericoesPressaoArterial/Create
        public ActionResult Create(int id)
        {
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", id);
            return View();
        }

        // POST: AfericoesPressaoArterial/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,DataHoraAfericao,Sistolica,Diastolica,ClienteId")] AfericaoPressaoArterial afericaoPressaoArterial)
        {
            if (ModelState.IsValid)
            {
                db.AfericoesPressaoArterial.Add(afericaoPressaoArterial);
                db.SaveChanges();
                return RedirectToAction("ByCliente", new { id = afericaoPressaoArterial.ClienteId });
            }

            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoPressaoArterial.ClienteId);
            return View(afericaoPressaoArterial);
        }

        // GET: AfericoesPressaoArterial/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoPressaoArterial afericaoPressaoArterial = db.AfericoesPressaoArterial.Find(id);
            if (afericaoPressaoArterial == null)
            {
                return HttpNotFound();
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoPressaoArterial.ClienteId);
            return View(afericaoPressaoArterial);
        }

        // POST: AfericoesPressaoArterial/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,DataHoraAfericao,Sistolica,Diastolica,ClienteId")] AfericaoPressaoArterial afericaoPressaoArterial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(afericaoPressaoArterial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ByCliente", new { id = afericaoPressaoArterial.ClienteId });
            }
            ViewBag.ClienteId = new SelectList(db.Clientes, "Id", "Nome", afericaoPressaoArterial.ClienteId);
            return View(afericaoPressaoArterial);
        }

        // GET: AfericoesPressaoArterial/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            AfericaoPressaoArterial afericaoPressaoArterial = db.AfericoesPressaoArterial.Find(id);
            if (afericaoPressaoArterial == null)
            {
                return HttpNotFound();
            }
            return View(afericaoPressaoArterial);
        }

        // POST: AfericoesPressaoArterial/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            AfericaoPressaoArterial afericaoPressaoArterial = db.AfericoesPressaoArterial.Find(id);
            db.AfericoesPressaoArterial.Remove(afericaoPressaoArterial);
            db.SaveChanges();
            return RedirectToAction("ByCliente", new { id = afericaoPressaoArterial.ClienteId });
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiUbs/SiUbs.WebApp/Controllers/ClientesController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using SiUbs.WebApp.Models;

namespace SiUbs.WebApp.Controllers
{
    [Authorize]
    public class ClientesController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: Clientes
        public ActionResult Index()
        {
            return View(db.Clientes.ToList());
        }

        // GET: Clientes/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // GET: Clientes/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Clientes/Create
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome,DataDeNascimento,Sexo")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Clientes.Add(cliente);
                db.SaveChanges();
                Request.RequestType = "POST";
                return RedirectToAction("SearchByName", new { name = cliente.Nome });
            }

            return View(cliente);
        }

        // GET: Clientes/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Edit/5
        // Para se proteger de mais ataques, ative as propriedades específicas a que você quer se conectar. Para 
        // obter mais detalhes, consulte http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome,DataDeNascimento,Sexo")] Cliente cliente)
        {
            if (ModelState.IsValid)
            {
                db.Entry(cliente).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Details", new { id = cliente.Id });
            }
            return View(cliente);
        }

        // GET: Clientes/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Cliente cliente = db.Clientes.Find(id);
            if (cliente == null)
            {
                return HttpNotFound();
            }
            return View(cliente);
        }

        // POST: Clientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Cliente cliente = db.Clientes.Find(id);
            db.Clientes.Remove(cliente);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet, ActionName("SearchByName")]
        [Route("{SearchByName/name:string}")]
        public ActionResult SearchByName(string name = "@")
        {
            var result = db.Clientes.Where(c => c.Nome.Contains(name));
            return View(result);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SiUbs/SiUbs.WebApp/Views/Clientes/Create.cshtml
@model SiUbs.WebApp.Models.Cliente

@{
    ViewBag.Title = "Novo Cliente";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiUbs/SiUbs.WebApp/Views/Clientes/Delete.cshtml
@model SiUbs.WebApp.Models.Cliente

@{
    ViewBag.Title = "Remover Cliente";
}

<h2>@ViewBag.Title</h2>

<h3>Tem certeza que deseja remover este registro?</h3>
<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-danger" />
        </div>
    }
    <div>
        @Html.ActionLink("Voltar", "Details", new { id = Model.Id })
    </div>
</div>

SiUbs/SiUbs.WebApp/Views/Clientes/Details.cshtml
@model SiUbs.WebApp.Models.Cliente

@{
    ViewBag.Title = "Detalhes";
}

<h2>@ViewBag.Title</h2>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Nome)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nome)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DataDeNascimento)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Sexo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Sexo)
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }, new { @class = "btn btn-primary" })
    @Html.ActionLink("Remover", "Delete", new { id = Model.Id }, new { @class = "btn btn-danger" })
</p>
<p>
    @Html.ActionLink("Voltar", "Index")
</p>

SiUbs/SiUbs.WebApp/Views/Clientes/Edit.cshtml
@model SiUbs.WebApp.Models.Cliente

@{
    ViewBag.Title = "Editar Cliente";
}

<h2>@ViewBag.Title</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Nome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DataDeNascimento, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DataDeNascimento, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DataDeNascimento, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Sexo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Sexo, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Sexo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar", "Details", new { id = Model.Id })
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

SiUbs/SiUbs.WebApp/Views/Clientes/Index.cshtml
@model IEnumerable<SiUbs.WebApp.Models.Cliente>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nome)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DataDeNascimento)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Sexo)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Nome)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DataDeNascimento)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Sexo)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>

SiUbs/SiUbs.WebApp/Views/Clientes/SearchByName.cshtml
@model IEnumerable<SiUbs.WebApp.Models.Cliente>

@{
    ViewBag.Title = "Clientes";
}

<div class="row">
    <div class="col-md-8">
        @using (Html.BeginForm("SearchByName", "Clientes", FormMethod.Get))
        {

            <div class="form-horizontal">
                <h2>Localizar Cliente</h2>
                <hr />
                <div class="row">
                    <div class="col-lg-12">
                        <h4>Digite o Nome do Cliente</h4>
                        <div class="input-group">
                            <input type="text" class="form-control" name="name" placeholder="(Caso não seja preenchido será listado TODOS os clientes cadastrados)" />
                            <span class="input-group-btn">
                                <input type="submit" value="Buscar..." class="btn btn-success" />
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
    <div class="col-md-4">
        <h2>Como Inserir Aferição <span class="glyphicon glyphicon-question-sign" aria-hidden="true"></span></h2>
        <p>Para inserir uma nova aferição busque o cliente pelo nome e em seguida adicione a aferição desejada utilizando os controles disponíveis ou cadastre um novo cliente por meio do botão abaixo.</p>
        @Html.ActionLink("Cadastrar Novo Cliente", "Create", null, new { @class = "btn btn-primary" })
    </div>
</div>

<br />

<div class="row">
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataDeNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Sexo)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Nome, "Details", new { id = item.Id })
                    
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataDeNascimento)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Sexo)
                </td>
                <td>
                    @Html.ActionLink("Glicemia", "ByCliente", "AfericoesGlicemia", new { id = item.Id },  new { @class = "btn btn-success" })
                    @Html.ActionLink("Pressão Arterial", "ByCliente", "AfericoesPressaoArterial", new { id = item.Id }, new { @class = "btn btn-success" })
                </td>
            </tr>
        }

    </table>
</div>